language: node_js
node_js:
  - 7
  - 6
  - 5
  - 4

cache:
  directories:
    - node_modules
branches:
  except: /^v\d+\.\d+\.\d+$/

before_script:
  - npm run build
after_script: 'cat ./coverage/lcov.info | coveralls'
after_success: 'npm run semantic-release'
